### How to model the project:
* initial state : Our initial state is the n*n matrix that we give as input to our algorithm.

* goal state : Our final state is actually when all the lights are off, or in other words, when all the elements in our n*n matrix are equal to zero.

* action : Here, the action that we can perform in each state is to hit one of the keys, which will change its value in the matrix along with its four neighboring keys, and therefore it will take us to a new state.

* transition model : As mentioned in the previous case, after each action, we change the value of that house from the matrix to all 4 neighboring houses.

In [1]:
import random
import heapq
from dataclasses import dataclass, field
from typing import List, Tuple, Callable, Any, Set
import numpy as np
from time import time
from tabulate import tabulate
import threading
import collections
from math import ceil
from enum import Enum

In [2]:
class LightsOutPuzzle:
    def __init__(self, board: List[List[int]]):
        self.board = np.array(board, dtype=np.uint8)
        self.size = len(board)

    def toggle(self, x, y):
        new_board = self.board.copy()
        for dx, dy in [(0, 0), (1, 0), (-1, 0), (0, 1), (0, -1)]:
            nx, ny = x + dx, y + dy
            if 0 <= nx < self.size and 0 <= ny < self.size:
                new_board[nx, ny] ^= 1
        return LightsOutPuzzle(new_board)


    def is_solved(self):
        return np.all(self.board == 0)

    def get_moves(self):
        return [(x, y) for x in range(self.size) for y in range(self.size)]

    def __str__(self):
        return '\n'.join(' '.join(str(cell) for cell in row) for row in self.board)


In [3]:
def create_random_board(size: int,  seed: int, num_toggles: int = None):
    random.seed(time() if seed is None else seed)

    board = [[0 for _ in range(size)] for _ in range(size)]
    puzzle = LightsOutPuzzle(board)

    if num_toggles is None:
        num_toggles = random.randint(1, size * size)

    for _ in range(num_toggles):
        x = random.randint(0, size - 1)
        y = random.randint(0, size - 1)
        puzzle = puzzle.toggle(x, y)

    return puzzle.board

In [4]:
def show_solution(
    puzzle: LightsOutPuzzle,
    solution: List[Tuple[int, int]],
    algorithm_name: str,
    nodes_visited: int,
    show_steps: bool = False,
):
    print(f"\nSolving with {algorithm_name}:")
    if solution is None:
        print("No solution found.")
        return
    print(f"Solution: {solution}")
    print(f"Nodes visited: {nodes_visited}")
    if show_steps:
        print("\nSolution steps:")
        for i, move in enumerate(solution):
            print(f"\nStep {i+1}: Toggle position {move}")
            puzzle.toggle(*move)
            print(puzzle)
        print(
            "\nFinal state (solved):"
            if puzzle.is_solved()
            else "\nFinal state (not solved):"
        )
        print(puzzle)

In [5]:
tests = [
    create_random_board(3, 42),
    create_random_board(3, 41),
    create_random_board(3, 42, 5),
    create_random_board(4, 42),
    create_random_board(4, 41),
    create_random_board(4, 42, 5),
    create_random_board(5, 42),
    create_random_board(5, 41),
    create_random_board(5, 42, 5),
]

### defind node for model the problem

In [6]:
class Node():
    def __init__(self, state, parent, action):
        self.state = state
        self.parent = parent
        self.action = action

### BFS

In this section, we want to implement the bfs algorithm. This algorithm exports each line of the tree completely and then moves to the next line. Therefore, considering that in uninformed algorithms, the cost of each action is equal, so the optimal solution is gives us, but since we check all the states, our processing time increases a lot

### defind a queue for BFS

In [7]:
class QueueFrontier:
    def __init__(self):
        self.frontier = []

    def add(self, node):
        self.frontier.append(node)

    def contains_state(self, state):
        return any(node.state == state for node in self.frontier)

    def empty(self):
        return len(self.frontier) == 0

    def remove(self):
        if self.empty():
            raise Exception("empty frontier")
        else:
            node = self.frontier[0]
            self.frontier = self.frontier[1:]
            return node

### BFS soloution

In [8]:
# TODO: Must return a list of tuples and the number of visited nodes     
from collections import deque
from typing import List, Tuple

# TODO: Must return a list of tuples and the number of visited nodes     
def bfs_solve(puzzle: LightsOutPuzzle) -> Tuple[List[Tuple[int, int]], int]:
    if puzzle.size >= 5:
        return [], 0
    
    num_explored = 0
    
    # Initialize frontier with the starting node
    start = Node(state=puzzle, parent=None, action=None)
    frontier = deque([start])
    
    # Set to track explored states
    explored = set()
    
    while frontier:
        # Remove the node from the frontier
        node = frontier.popleft()
        
        # If the state has already been explored, skip it
        if node.state in explored:
            continue

        # Mark as explored
        explored.add(node.state)
        num_explored += 1

        # If the goal state is found
        if node.state.is_solved():
            actions = []
            while node.parent is not None:
                actions.append(node.action)
                node = node.parent
            actions.reverse()
            return actions, num_explored

        # Add neighbors (possible moves) to the frontier
        for move in node.state.get_moves():
            new_state = node.state.toggle(move[0], move[1])
            if new_state not in explored:
                child = Node(state=new_state, parent=node, action=move)
                frontier.append(child)

    # If no solution is found
    raise Exception("No solution")

                

In [9]:
board = [[0,1,1,0],[1,0,0,1],[0,1,1,0],[0,0,0,0]]
puzzle = LightsOutPuzzle(board)
print(bfs_solve(puzzle))

([(1, 1), (1, 2)], 104)


### IDS

aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

### defind a stack for IDS

In [10]:
class StackFrontier(QueueFrontier):
    def remove(self):
        if self.empty():
            raise Exception("empty frontier")
        else:
            node = self.frontier[-1]
            self.frontier = self.frontier[:-1]
            return node

### Depth-limited search function for IDS algorithm

In [11]:
def dls_solve(node: Node, limit: int, explored: set, num_explored: int) -> Tuple[List[Tuple[int, int]], int]:
    # If node is the goal, return the solution
    if node.state.is_solved():
        actions = []
        while node.parent is not None:
            actions.append(node.action)
            node = node.parent
        actions.reverse()
        return actions, num_explored

    # If reached the depth limit, stop the search
    if limit == 0:
        return None, num_explored
    
    # Mark node as explored
    explored.add(node.state)

    # Get the list of neighbors
    neighbors = []
    moves = node.state.get_moves()
    for move in moves:
        neighbors.append((move, node.state.toggle(move[0],move[1])))

    # Recursively explore neighbors, respecting the depth limit
    for action, state in neighbors:
        if state not in explored:
            child = Node(state=state, parent=node, action=action)
            result, num_explored = dls_solve(child, limit - 1, explored, num_explored + 1)
            if result is not None:
                return result, num_explored

    return None, num_explored


### IDS soloution

In [12]:
# TODO: Must return a list of tuples and the number of visited nodes
def ids_solve(puzzle: LightsOutPuzzle) -> Tuple[List[Tuple[int, int]], int]:
    if puzzle.size >= 5:
        return [], 0
    
    num_explored = 0
    
    # Keep trying with increasing depth limits
    for depth in range(1000):  # Arbitrary large limit to avoid infinite loop
        explored = set()
        start = Node(state=puzzle, parent=None, action=None)
        result, num_explored = dls_solve(start, depth, explored, num_explored)
        if result is not None:
            return result, num_explored

    raise Exception("no solution")

In [13]:
board = [[0,1,1,0],[1,0,0,1],[0,1,1,0],[0,0,0,0]]
puzzle = LightsOutPuzzle(board)
print(ids_solve(puzzle))

([(1, 1), (1, 2)], 109)


### A* Algorithm

In this section, we want to implement the bfs algorithm. This algorithm exports each line of the tree completely and then moves to the next line. Therefore, considering that in uninformed algorithms, the cost of each action is equal, so the optimal solution is gives us, but since we check all the states, our processing time increases a lot

In [14]:
# TODO: Must return a list of tuples and the number of visited nodes
def astar_solve(puzzle: LightsOutPuzzle, heuristic: Callable[[LightsOutPuzzle], int]) -> Tuple[List[Tuple[int, int]], int]:
    num_explored = 0
    
    # Frontier as a list
    frontier = []
    
    # Initialize the starting node with g = 0 (cost so far)
    start = Node(state=puzzle, parent=None, action=None)
    g = 0
    h = heuristic(puzzle)
    f = g + h
    frontier.append((f, g, start))  # Append tuple (f, g, node)
    
    # Set to keep track of explored states
    explored = set()
    
    while frontier:
        # Select the node with the lowest f score
        frontier.sort(key=lambda x: x[0])  # Sort by f value
        f, g, node = frontier.pop(0)  # Remove the node with the smallest f
        num_explored += 1

        # If this state is the goal, reconstruct the path to the solution
        if node.state.is_solved():
            actions = []
            while node.parent is not None:
                actions.append(node.action)
                node = node.parent
            actions.reverse()  # Reverse to get the correct order of actions
            return actions, num_explored
        
        # Mark the node as explored
        explored.add(node.state)

        # Explore neighbors (possible moves)
        moves = node.state.get_moves()
        for move in moves:
            new_state = node.state.toggle(move[0], move[1])
            
            if new_state not in explored:
                # Calculate new g, h, and f values
                new_g = g + 1  # Each move costs 1
                new_h = heuristic(new_state)
                new_f = new_g + new_h
                
                # Add the new node to the frontier
                child = Node(state=new_state, parent=node, action=move)
                frontier.append((new_f, new_g, child))

    raise Exception("No solution found")

### simple heuristic
in this heuristic we just count the number of 1's

In [15]:
# TODO: Implement heuristic functions and store them in the list

def heuristic_based_on_ones(puzzle: LightsOutPuzzle):
  return np.sum(puzzle.board)


### mod 5 heuristic

shdljshdljfhsljdfljsdflsdf

In [16]:
def mod_five_heuristic(puzzle : LightsOutPuzzle):
    return np.sum(puzzle.board)/5

### Cluster of 1s heuristic

kjfljefkerfer

In [17]:
def cluster_ones_heuristic(puzzle : LightsOutPuzzle):
    puzzle_array = puzzle.board  # Assuming puzzle.grid is a 2D list representing the puzzle
    # Create shifted versions of the puzzle grid to represent the neighbors
    up = np.roll(puzzle_array, shift=-1, axis=0)
    down = np.roll(puzzle_array, shift=1, axis=0)
    left = np.roll(puzzle_array, shift=-1, axis=1)
    right = np.roll(puzzle_array, shift=1, axis=1)
    # Sum the neighbors, including the cell itself
    neighbor_sum = puzzle_array + up + down + left + right
    # Count cells where the sum of itself and its neighbors is 3 or more
    cluster_num = np.sum(neighbor_sum >= 3)
    
    return cluster_num

In [18]:
board = [[0,1,1,0],[1,0,0,1],[0,1,1,0],[0,0,0,0]]
puzzle = LightsOutPuzzle(board)
print(astar_solve(puzzle,mod_five_heuristic))

([(1, 1), (1, 2)], 6)


In [19]:

heuristics = [heuristic_based_on_ones, mod_five_heuristic, cluster_ones_heuristic]
# heuristics = []

In [20]:
# TODO: Implement weighted heuristic functions and store them in the list
def weighted_heuristic1(puzzle: LightsOutPuzzle, alpha = 5):
  return mod_five_heuristic(puzzle) * alpha

weighted_heuristics = [weighted_heuristic1]

# TODO: assign 2 weights you wanna run
weights = [2, 4]

In [21]:
board = [[0,1,1,0],[1,0,0,1],[0,1,1,0],[0,0,0,0]]
puzzle = LightsOutPuzzle(board)
print(astar_solve(puzzle,weighted_heuristic1))

([(1, 1), (1, 2)], 5)


In [22]:
class SearchStatus(Enum):
    SOLVED = "Solved"
    TIMEOUT = "Timeout"
    NO_SOLUTION = "No Solution"

@dataclass
class SearchResult:
    result: SearchStatus
    solution: Any = None
    nodes_visited: int = None
    time: float = None

    def __str__(self):
        output = f"Result: {self.result.value}\n"
        if self.result == SearchStatus.SOLVED:
            output += f"Solution: {self.solution}\n"
        if self.result != SearchStatus.TIMEOUT:
            output += f"Nodes Visited: {self.nodes_visited}\n"
            output += f"Time Taken: {self.time:.3f} seconds\n"

        return output


DEFAULT_SEARCH_RESULT = SearchResult(SearchStatus.TIMEOUT, None, None, float("inf"))

In [23]:
def run_searches(func: Callable, args: Any, time_limit: float = 60.0, name: str = "") -> SearchResult:
    result = []

    def target():
        try:
            solution, nodes_visited = func(*args)
            result.append((solution, nodes_visited))
        except Exception as e:
            result.append(e)

    thread = threading.Thread(target=target)
    thread.start()

    start_time = time()
    thread.join(timeout=time_limit)

    if thread.is_alive() or not result:
        print(f"\nTime limit of {time_limit} seconds exceeded for {name}")
        return SearchResult(SearchStatus.TIMEOUT)

    if isinstance(result[0], Exception):
        raise result[0]

    solution, nodes_visited = result[0]
    show_solution(args[0], solution, name, nodes_visited)
    time_taken = time() - start_time
    return SearchResult(SearchStatus.SOLVED if solution else SearchStatus.NO_SOLUTION, solution, nodes_visited, time_taken)

In [24]:
from functools import partial


def run_test(test: List, heuristics: List[Callable[[Any], int]], time_limit: float = 60.0):

    print(f"Running test:\n {test}")

    puzzle = LightsOutPuzzle(test)

    bfs_result = run_searches(bfs_solve, (puzzle,), name="BFS", time_limit=time_limit)
    ids_result = run_searches(ids_solve, (puzzle,), name="IDS", time_limit=time_limit)

    astar_results = []
    for heuristic in heuristics:
        astar_results.append(
            run_searches(
                astar_solve,
                (puzzle, heuristic),
                name=f"A*({heuristic.__name__})",
                time_limit=time_limit,
            )
        )

    weighted_astar_results = []
    for heuristic in weighted_heuristics:
        for weight in weights:
          weighted_astar_results.append(
              run_searches(
                  astar_solve,
                  (puzzle, partial(heuristic, alpha = weight)),
                  name=f"weighted A*({heuristic.__name__}, alpha = {weight})",
                  time_limit=time_limit,
              )
          )

    print("\n-------------------------------\n")

    return (
        test,
        bfs_result,
        ids_result,
        *astar_results,
        *weighted_astar_results
    )

In [25]:
results: List[Tuple[str, SearchResult, SearchResult, SearchResult, SearchResult]] = []

for test in tests:
    results.append(run_test(test, heuristics, 120))

Running test:
 [[1 1 1]
 [1 1 1]
 [1 0 0]]

Solving with BFS:
Solution: [(0, 2), (1, 0)]
Nodes visited: 32

Solving with IDS:
Solution: [(0, 2), (1, 0)]
Nodes visited: 34

Solving with A*(heuristic_based_on_ones):
Solution: [(1, 0), (0, 2)]
Nodes visited: 4

Solving with A*(mod_five_heuristic):
Solution: [(1, 0), (0, 2)]
Nodes visited: 8

Solving with A*(cluster_ones_heuristic):
Solution: [(1, 0), (0, 2)]
Nodes visited: 5

Solving with weighted A*(weighted_heuristic1, alpha = 2):
Solution: [(1, 0), (0, 2)]
Nodes visited: 4

Solving with weighted A*(weighted_heuristic1, alpha = 4):
Solution: [(1, 0), (0, 2)]
Nodes visited: 4

-------------------------------

Running test:
 [[1 1 0]
 [1 0 0]
 [1 1 1]]

Solving with BFS:
Solution: [(0, 0), (0, 1), (1, 0), (1, 1), (1, 2)]
Nodes visited: 8395

Solving with IDS:
Solution: [(0, 0), (0, 1), (1, 0), (1, 1), (1, 2)]
Nodes visited: 9441

Solving with A*(heuristic_based_on_ones):
Solution: [(1, 0), (1, 1), (1, 2), (0, 1), (0, 0)]
Nodes visited: 59

In [26]:
table_data: List[List[str]] = []

for result in results:
    table_data.append(
        [
            "\n".join(" ".join(str(cell) for cell in row) for row in result[0]),
            str(result[1]),
            str(result[2]),
        ]
    )

    for i in range(len(heuristics)):
        table_data[-1].append(str(result[3 + i]))

    for i in range(len(weighted_heuristics)):
        for j in range(len(weights)):
          table_data[-1].append(str(result[3 + len(heuristics) + i * 2 + j]))

    table_data.append("\n\n\n")

if table_data[-1] == "\n\n\n":
    table_data.pop()

print(len(table_data))
print("Results:")
print(
    tabulate(
        table_data,
        headers=[
            "Test",
            "BFS",
            "IDS",
            *[f"A* ({heuristic.__name__})" for heuristic in heuristics],
            *[f"Weighted A* ({heuristic.__name__}, alpha = {weight})" for heuristic in weighted_heuristics for weight in weights]
        ],
        floatfmt=".3f",
        numalign="center",
        stralign="center",
        tablefmt="grid",
    )
)

17
Results:
+-----------+----------------------------------------------------+----------------------------------------------------+--------------------------------------------------------------------+----------------------------------------------------+----------------------------------------------------+----------------------------------------------------+--------------------------------------------------------------------+
|   Test    |                        BFS                         |                        IDS                         |                    A* (heuristic_based_on_ones)                    |              A* (mod_five_heuristic)               |            A* (cluster_ones_heuristic)             |    Weighted A* (weighted_heuristic1, alpha = 2)    |            Weighted A* (weighted_heuristic1, alpha = 4)            |
+===========+====================================================+====================================================+===================================